#!/usr/bin/env bash
# cron.sh — nightly OpenCastor AutoResearcher wrapper
# Cron: 0 0 * * * /home/craigm26/opencastor-autoresearch/cron.sh >> /home/craigm26/autoresearch.log 2>&1

set -euo pipefail

REPO="/home/craigm26/opencastor-autoresearch"
OC_REPO="/home/craigm26/OpenCastor"
LOG="$REPO/run.log"
BRANCH="autoresearch/$(date +%Y-%m-%d)"

# Load env
source "$REPO/.env"
export OPENCASTOR_REPO_PATH="$OC_REPO"

# ── Track rotation (ISO day 1=Mon…7=Sun) ──────────────────────────────────────
DOW=$(date +%u)
case $DOW in
  1|4) export TODAY_TRACK="A" ;;   # Mon, Thu = Tests
  2|5) export TODAY_TRACK="B" ;;   # Tue, Fri = Docstrings
  3)   export TODAY_TRACK="C" ;;   # Wed      = Presets
  6)   export TODAY_TRACK="D" ;;   # Sat      = Skill improvements
  7)   export TODAY_TRACK="E" ;;   # Sun      = Harness/P66 tests
esac

echo "[cron] $(date) — Starting track=$TODAY_TRACK branch=$BRANCH"

# ── Create / checkout dated branch in OpenCastor ─────────────────────────────
cd "$OC_REPO"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# ── Reviewer auth ────────────────────────────────────────────────────────────
# REVIEWER_TOKEN: Bearer token for the reviewer robot's /api/chat endpoint.
# Needed when the reviewer robot runs with hardened auth (returns 401 otherwise).
# Set this to the API token configured in the reviewer robot's OpenCastor instance.
# Overrides OPENCASTOR_API_TOKEN for reviewer calls specifically.
# Example: export REVIEWER_TOKEN="oc-tok-xxxxxxxxxxxx"
# If unset, autoresearch degrades gracefully (logs a warning, falls back to Gemini ADC).
# export REVIEWER_TOKEN=""

# ── Reviewer routing ─────────────────────────────────────────────────────────
# If Alex (RRN-000000000005) is reachable, use RCAN review. Otherwise Gemini ADC.
if curl -sf --connect-timeout 3 "http://alex.local:8000/health" >/dev/null 2>&1; then
    export REVIEWER="rcan"
    export REVIEWER_RRN="RRN-000000000005"
    export REVIEWER_URL="http://alex.local:8000"
    echo "[cron] $(date) — Alex online, using RCAN review"
else
    export REVIEWER="gemini"
    echo "[cron] $(date) — Alex offline, using Gemini ADC review"
fi

# ── Main run (midnight–6am = 6h) ──────────────────────────────────────────────
cd "$REPO"
timeout 21600 "$REPO/.venv/bin/python3" run_agent.py > "$LOG" 2>&1 || true

echo "[cron] $(date) — Agent stopped. Committing results..."

# ── Commit results.tsv ────────────────────────────────────────────────────────
cd "$OC_REPO"
git add -A 2>/dev/null || true
if ! git diff --staged --quiet; then
    git commit -m "auto: nightly results $(date +%Y-%m-%d) track=$TODAY_TRACK"
fi

# Count experiments
KEPT=$(grep -c $'\tkeep\t' "$REPO/results.tsv" 2>/dev/null || echo 0)
TOTAL=$(awk 'NR>1' "$REPO/results.tsv" 2>/dev/null | wc -l || echo 0)

echo "[cron] $(date) — $KEPT/$TOTAL experiments kept. Opening PR..."

# ── Open GitHub PR (best-effort) ──────────────────────────────────────────────
gh pr create \
    --title "autoresearch $(date +%Y-%m-%d): track=$TODAY_TRACK ($KEPT/$TOTAL kept)" \
    --body "$(cat <<PREOF
## Nightly AutoResearch Summary

**Track:** $TODAY_TRACK
**Date:** $(date +%Y-%m-%d)
**Model:** qwen2.5-coder:3b (or gemma3:1b fallback)
**Experiments:** $TOTAL total, $KEPT kept

### Results

\`\`\`
$(tail -20 "$REPO/results.tsv" 2>/dev/null || echo "no results")
\`\`\`

Auto-generated by [opencastor-autoresearch](https://github.com/craigm26/opencastor-autoresearch)
PREOF
)" \
    --base main \
    --head "$BRANCH" 2>/dev/null \
    || echo "[cron] PR creation skipped (no new commits or already exists)"

# ── Track F: trajectory mining at 2am (runs after main loop exits) ────────────
HOUR=$(date +%H)
if [[ "$HOUR" -ge 2 && "$HOUR" -lt 4 ]]; then
    echo "[cron] $(date) — Running Track F (trajectory mining)..."
    export TODAY_TRACK="F"
    timeout 1800 "$REPO/.venv/bin/python3" run_agent.py >> "$LOG" 2>&1 || true
fi

# ── Harness research (10 AM daily) ─────────────────────────────────────────────
# 0 10 * * * cd /home/craigm26/opencastor-autoresearch && python harness_research/run.py >> /tmp/harness_research.log 2>&1

echo "[cron] $(date) — Done."
