#!/usr/bin/env bash
# cron.sh — nightly OpenCastor AutoResearcher wrapper
# Cron: 0 0 * * * /home/craigm26/opencastor-autoresearch/cron.sh >> /home/craigm26/autoresearch.log 2>&1

set -euo pipefail

REPO="/home/craigm26/opencastor-autoresearch"
OC_REPO="/home/craigm26/OpenCastor"
LOG="$REPO/run.log"
BRANCH="autoresearch/$(date +%Y-%m-%d)"

# Load env
# shellcheck source=.env
source "$REPO/.env"
export OPENCASTOR_REPO_PATH="$OC_REPO"

# Determine track by ISO day of week (1=Mon ... 7=Sun)
DOW=$(date +%u)
case $DOW in
  1|4) export TODAY_TRACK="A" ;;  # Mon, Thu = Tests
  2|5) export TODAY_TRACK="B" ;;  # Tue, Fri = Docs
  3|6) export TODAY_TRACK="C" ;;  # Wed, Sat = Presets
  7)   export TODAY_TRACK="A" ;;  # Sun = Tests (default)
esac

echo "[cron] $(date) — Starting track=$TODAY_TRACK branch=$BRANCH"

# Create or check out dated branch in OpenCastor repo
cd "$OC_REPO"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Run agent for 6 hours (midnight–6am)
cd "$REPO"
timeout 21600 python3 run_agent.py > "$LOG" 2>&1 || true

echo "[cron] $(date) — Agent stopped. Committing results..."

# Commit results.tsv and run.log if there are changes
cd "$OC_REPO"
git add results.tsv run.log 2>/dev/null || true
if ! git diff --staged --quiet; then
  git commit -m "auto: nightly results $(date +%Y-%m-%d) track=$TODAY_TRACK"
fi

# Count experiments
KEPT=$(grep -c "keep" "$REPO/results.tsv" 2>/dev/null || echo 0)
TOTAL=$(grep -vc "^commit" "$REPO/results.tsv" 2>/dev/null || echo 0)

echo "[cron] $(date) — $KEPT/$TOTAL experiments kept. Opening PR..."

# Open GitHub PR (best-effort — don't fail if no changes)
gh pr create \
  --title "autoresearch $(date +%Y-%m-%d): track=$TODAY_TRACK ($KEPT/$TOTAL kept)" \
  --body "$(cat <<PREOF
## Nightly AutoResearch Summary

**Track:** $TODAY_TRACK
**Date:** $(date +%Y-%m-%d)
**Experiments:** $TOTAL total, $KEPT kept

### Results

\`\`\`
$(column -t "$REPO/results.tsv" 2>/dev/null || cat "$REPO/results.tsv")
\`\`\`

Auto-generated by [opencastor-autoresearch](https://github.com/craigm26/opencastor-autoresearch)
PREOF
)" \
  --base main \
  --head "$BRANCH" 2>/dev/null || echo "[cron] PR creation skipped (no new commits or already exists)"

echo "[cron] $(date) — Done."
