"""Promote winning harness config to OpenCastor after approval."""

import logging
import subprocess
from datetime import date
from pathlib import Path

import yaml

log = logging.getLogger(__name__)

OPS_REPO = Path.home() / "opencastor-ops"
CHAMPION_PATH = OPS_REPO / "harness-research" / "champion.yaml"
OPENCASTOR_REPO = Path.home() / "OpenCastor"
TARGET_HARNESS = OPENCASTOR_REPO / "castor" / "harness" / "default_harness.yaml"


def _run(args: list[str], cwd: Path) -> str:
    """Run a command and return stdout."""
    result = subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()


def promote(dry_run: bool = False) -> bool:
    """Read champion.yaml and open PR in OpenCastor with the winning config.

    Returns True if promotion PR was created successfully.
    """
    if not CHAMPION_PATH.exists():
        log.error("No champion.yaml found at %s", CHAMPION_PATH)
        return False

    champion = yaml.safe_load(CHAMPION_PATH.read_text())
    if not champion or not champion.get("config"):
        log.error("Champion.yaml is empty or missing config")
        return False

    config = champion["config"]
    score = champion.get("score", 0.0)
    champion_date = champion.get("date", date.today().isoformat())
    today = date.today().isoformat()

    log.info(
        "Promoting champion: score=%.4f date=%s candidate=%s",
        score,
        champion_date,
        champion.get("candidate_id", "unknown"),
    )

    if dry_run:
        log.info("[dry-run] Would write config to %s", TARGET_HARNESS)
        log.info("[dry-run] Config: %s", config)
        return True

    branch = f"harness-update/{today}"

    try:
        # Ensure we're on main and up to date
        _run(["git", "checkout", "main"], cwd=OPENCASTOR_REPO)
        _run(["git", "pull", "--ff-only"], cwd=OPENCASTOR_REPO)

        # Create branch
        _run(["git", "checkout", "-b", branch], cwd=OPENCASTOR_REPO)

        # Write harness config
        TARGET_HARNESS.parent.mkdir(parents=True, exist_ok=True)
        harness_data = {
            "# Auto-generated by harness-research pipeline": None,
            "# Source": f"champion from {champion_date}",
            **config,
        }
        # Write clean YAML without the comment keys
        output_lines = [
            f"# Auto-generated by harness-research pipeline",
            f"# Source: champion from {champion_date}, score {score:.4f}",
            "",
            yaml.dump(config, default_flow_style=False).strip(),
            "",
        ]
        TARGET_HARNESS.write_text("\n".join(output_lines))
        log.info("Harness config written to %s", TARGET_HARNESS)

        # Commit and push
        _run(["git", "add", str(TARGET_HARNESS)], cwd=OPENCASTOR_REPO)
        _run(
            ["git", "commit", "-m",
             f"feat(harness): update default agent harness {today}"],
            cwd=OPENCASTOR_REPO,
        )
        _run(["git", "push", "-u", "origin", branch], cwd=OPENCASTOR_REPO)

        # Create PR
        pr_body = (
            f"## Harness Update — {today}\n\n"
            f"Promoted from harness-research champion.\n\n"
            f"- **Score:** {score:.4f}\n"
            f"- **Candidate:** {champion.get('candidate_id', 'N/A')}\n"
            f"- **Description:** {champion.get('description', 'N/A')}\n"
        )
        result = _run(
            [
                "gh", "pr", "create",
                "--repo", "craigm26/OpenCastor",
                "--head", branch,
                "--base", "main",
                "--title", f"feat(harness): update default agent harness {today}",
                "--body", pr_body,
                "--label", "harness-update",
            ],
            cwd=OPENCASTOR_REPO,
        )
        log.info("PR created: %s", result)

        # Enable auto-merge
        # Extract PR number from URL
        pr_number = result.strip().split("/")[-1]
        _run(
            ["gh", "pr", "merge", "--auto", "--squash", pr_number,
             "--repo", "craigm26/OpenCastor"],
            cwd=OPENCASTOR_REPO,
        )
        log.info("Auto-merge enabled for PR #%s", pr_number)

        # Return to main
        _run(["git", "checkout", "main"], cwd=OPENCASTOR_REPO)

    except subprocess.CalledProcessError as e:
        log.error("Promotion failed: %s\n%s", e, e.stderr)
        try:
            _run(["git", "checkout", "main"], cwd=OPENCASTOR_REPO)
        except subprocess.CalledProcessError:
            pass
        raise

    return True


if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    dry = "--dry-run" in sys.argv
    promote(dry_run=dry)
