"""Generate reports and manage champion updates for harness research results."""

import logging
import os
import subprocess
from datetime import date
from pathlib import Path

import yaml

from .evaluator import EvalResults
from .ranker import compute_score

log = logging.getLogger(__name__)

# Allow CI to override the ops repo path via env var
OPS_REPO = Path(os.environ.get("OPENCASTOR_OPS_DIR", Path.home() / "opencastor-ops"))
HARNESS_DIR = OPS_REPO / "harness-research"
CANDIDATES_DIR = HARNESS_DIR / "candidates"
CHAMPION_PATH = HARNESS_DIR / "champion.yaml"
PROFILES_DIR = HARNESS_DIR / "profiles"


def _run_git(args: list[str], cwd: Path) -> str:
    """Run a git command in the given directory."""
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _sanitize_model_id(model_id: str) -> str:
    """Sanitize model_id for use in file paths (replace / with _)."""
    return model_id.replace("/", "_")


def _ensure_dirs(hardware_tier: str | None = None, model_id: str | None = None):
    """Ensure the harness-research directory structure exists."""
    CANDIDATES_DIR.mkdir(parents=True, exist_ok=True)
    if hardware_tier and model_id:
        (PROFILES_DIR / hardware_tier).mkdir(parents=True, exist_ok=True)
    elif hardware_tier:
        PROFILES_DIR.mkdir(parents=True, exist_ok=True)


def _generate_report_md(
    ranked: list[tuple[EvalResults, float]],
    winner: EvalResults | None,
    champion_score: float,
    today: str,
    hardware_tier: str | None = None,
    model_id: str | None = None,
) -> str:
    """Generate markdown report content."""
    tier_label = f" [{hardware_tier}]" if hardware_tier else " [generic]"
    model_label = f" [{model_id}]" if model_id else ""
    lines = [
        f"# Harness Research Report — {today}{tier_label}{model_label}",
        "",
        f"**Hardware tier:** {hardware_tier or 'generic'}",
        *([f"**Model:** {model_id}"] if model_id else []),
        f"**Champion score:** {champion_score:.4f}",
        f"**Candidates evaluated:** {len(ranked)}",
        f"**Winner:** {'Yes — ' + winner.candidate_id if winner else 'No improvement found'}",
        "",
        "## Candidate Rankings",
        "",
        "| Rank | ID | Score | Success | P66 | Efficiency | Latency | Description |",
        "|------|----|-------|---------|-----|------------|---------|-------------|",
    ]

    for i, (result, score) in enumerate(ranked, 1):
        marker = " ⭐" if winner and result.candidate_id == winner.candidate_id else ""
        lines.append(
            f"| {i} | {result.candidate_id}{marker} | {score:.4f} "
            f"| {result.success_rate:.2f} | {result.p66_rate:.2f} "
            f"| {result.token_efficiency:.2f} | {result.latency_score:.2f} "
            f"| {result.description} |"
        )

    if winner:
        lines.extend([
            "",
            "## Winner Details",
            "",
            f"**ID:** {winner.candidate_id}",
            f"**Score:** {compute_score(winner):.4f} (champion: {champion_score:.4f})",
            f"**Description:** {winner.description}",
            "",
            "### Config",
            "```yaml",
            yaml.dump(winner.config, default_flow_style=False).strip(),
            "```",
            "",
            "### Environment Breakdown",
            "",
        ])
        for env in ["home", "industrial", "general"]:
            agg = winner.env_aggregate(env)
            lines.append(
                f"- **{env}**: success={agg['success_rate']:.2f} "
                f"p66={agg['p66_rate']:.2f} (n={agg['count']})"
            )

    lines.extend(["", "---", f"Generated by harness-research pipeline on {today}"])
    return "\n".join(lines)


def write_report(
    ranked: list[tuple[EvalResults, float]],
    winner: EvalResults | None,
    champion_score: float,
    dry_run: bool = False,
    hardware_tier: str | None = None,
    model_id: str | None = None,
) -> bool:
    """Write report and update champion/profile champion.

    Args:
        ranked: Sorted list of (EvalResults, score) tuples.
        winner: Winning candidate or None if no improvement.
        champion_score: Current champion's score.
        dry_run: Skip all file and git operations.
        hardware_tier: If set, update profiles/<tier>.yaml instead of/alongside champion.yaml.
        model_id: If set, write to profiles/{tier}/{model_id_sanitized}.yaml and
            add _{model_id_sanitized} suffix to filenames.

    Returns True if a winner was found and committed.
    """
    today = date.today().isoformat()
    model_sanitized = _sanitize_model_id(model_id) if model_id else None
    _ensure_dirs(hardware_tier=hardware_tier, model_id=model_id)

    report_md = _generate_report_md(ranked, winner, champion_score, today, hardware_tier, model_id)
    tier_suffix = f"-{hardware_tier}" if hardware_tier else ""
    model_suffix = f"_{model_sanitized}" if model_sanitized else ""
    report_path = HARNESS_DIR / f"{today}{tier_suffix}{model_suffix}.md"

    if dry_run:
        log.info("[dry-run] Would write report to %s", report_path)
        log.info("[dry-run] Report preview:\n%s", report_md[:500])
        return winner is not None

    # Write report
    report_path.write_text(report_md)
    log.info("Report written to %s", report_path)

    if not winner:
        log.info("No winner — skipping champion update")
        return False

    winner_score = compute_score(winner)

    # Write winning config to candidates dir
    winner_path = CANDIDATES_DIR / f"{today}{tier_suffix}{model_suffix}-winner.yaml"
    winner_data = {
        "id": winner.candidate_id,
        "date": today,
        "score": winner_score,
        "hardware_tier": hardware_tier,
        **({"model_id": model_id} if model_id else {}),
        "description": winner.description,
        "config": winner.config,
    }
    winner_path.write_text(yaml.dump(winner_data, default_flow_style=False))
    log.info("Winner config written to %s", winner_path)

    # Update per-tier + per-model profile champion
    if hardware_tier and model_id:
        profile_path = PROFILES_DIR / hardware_tier / f"{model_sanitized}.yaml"
        profile_data = {
            "hardware_tier": hardware_tier,
            "model_id": model_id,
            "score": winner_score,
            "date": today,
            "candidate_id": winner.candidate_id,
            "description": winner.description,
            "config": winner.config,
        }
        profile_path.write_text(yaml.dump(profile_data, default_flow_style=False))
        log.info("Profile champion updated: %s/%s (score=%.4f)", hardware_tier, model_id, winner_score)
    elif hardware_tier:
        profile_path = PROFILES_DIR / f"{hardware_tier}.yaml"
        profile_data = {
            "hardware_tier": hardware_tier,
            "score": winner_score,
            "date": today,
            "candidate_id": winner.candidate_id,
            "description": winner.description,
            "config": winner.config,
        }
        profile_path.write_text(yaml.dump(profile_data, default_flow_style=False))
        log.info("Profile champion updated: %s (score=%.4f)", hardware_tier, winner_score)

    # Update generic champion.yaml only when running without a hardware tier
    if not hardware_tier:
        champion_data = {
            "score": winner_score,
            "date": today,
            "candidate_id": winner.candidate_id,
            "description": winner.description,
            "config": winner.config,
        }
        CHAMPION_PATH.write_text(yaml.dump(champion_data, default_flow_style=False))
        log.info("Generic champion updated: score=%.4f", winner_score)

    # Commit and push to opencastor-ops
    try:
        _run_git(["add", "harness-research/"], cwd=OPS_REPO)
        tier_tag = f"[{hardware_tier}] " if hardware_tier else ""
        _run_git(
            ["commit", "-m",
             f"feat(harness-research): {tier_tag}results {today} "
             f"[{winner.candidate_id}, score={winner_score:.4f}]"],
            cwd=OPS_REPO,
        )
        _run_git(["push", "origin", "HEAD"], cwd=OPS_REPO)
        log.info("Pushed harness research results to opencastor-ops")
    except subprocess.CalledProcessError as e:
        log.error("Git push to opencastor-ops failed: %s\n%s", e, e.stderr)
        raise

    return True
