"""Generate reports and manage PR workflow for harness research results."""

import logging
import os
import subprocess
from datetime import date
from pathlib import Path

import yaml

from .evaluator import EvalResults
from .ranker import compute_score

log = logging.getLogger(__name__)

# Allow CI to override the ops repo path via env var
OPS_REPO = Path(os.environ.get("OPENCASTOR_OPS_DIR", Path.home() / "opencastor-ops"))
HARNESS_DIR = OPS_REPO / "harness-research"
CANDIDATES_DIR = HARNESS_DIR / "candidates"
CHAMPION_PATH = HARNESS_DIR / "champion.yaml"


def _run_git(args: list[str], cwd: Path) -> str:
    """Run a git command in the given directory."""
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _ensure_dirs():
    """Ensure the harness-research directory structure exists."""
    CANDIDATES_DIR.mkdir(parents=True, exist_ok=True)


def _generate_report_md(
    ranked: list[tuple[EvalResults, float]],
    winner: EvalResults | None,
    champion_score: float,
    today: str,
) -> str:
    """Generate markdown report content."""
    lines = [
        f"# Harness Research Report — {today}",
        "",
        f"**Champion score:** {champion_score:.4f}",
        f"**Candidates evaluated:** {len(ranked)}",
        f"**Winner:** {'Yes — ' + winner.candidate_id if winner else 'No improvement found'}",
        "",
        "## Candidate Rankings",
        "",
        "| Rank | ID | Score | Success | P66 | Efficiency | Latency | Description |",
        "|------|----|-------|---------|-----|------------|---------|-------------|",
    ]

    for i, (result, score) in enumerate(ranked, 1):
        marker = " ⭐" if winner and result.candidate_id == winner.candidate_id else ""
        lines.append(
            f"| {i} | {result.candidate_id}{marker} | {score:.4f} "
            f"| {result.success_rate:.2f} | {result.p66_rate:.2f} "
            f"| {result.token_efficiency:.2f} | {result.latency_score:.2f} "
            f"| {result.description} |"
        )

    if winner:
        lines.extend([
            "",
            "## Winner Details",
            "",
            f"**ID:** {winner.candidate_id}",
            f"**Score:** {compute_score(winner):.4f} (champion: {champion_score:.4f})",
            f"**Description:** {winner.description}",
            "",
            "### Config",
            "```yaml",
            yaml.dump(winner.config, default_flow_style=False).strip(),
            "```",
            "",
            "### Environment Breakdown",
            "",
        ])
        for env in ["home", "industrial", "general"]:
            agg = winner.env_aggregate(env)
            lines.append(
                f"- **{env}**: success={agg['success_rate']:.2f} "
                f"p66={agg['p66_rate']:.2f} (n={agg['count']})"
            )

    lines.extend(["", f"---", f"Generated by harness-research pipeline on {today}"])
    return "\n".join(lines)


def write_report(
    ranked: list[tuple[EvalResults, float]],
    winner: EvalResults | None,
    champion_score: float,
    dry_run: bool = False,
) -> bool:
    """Write report and optionally create PR.

    Returns True if a winner was found and reported.
    """
    today = date.today().isoformat()
    _ensure_dirs()

    report_md = _generate_report_md(ranked, winner, champion_score, today)
    report_path = HARNESS_DIR / f"{today}.md"

    if dry_run:
        log.info("[dry-run] Would write report to %s", report_path)
        log.info("[dry-run] Report preview:\n%s", report_md[:500])
        return winner is not None

    # Write report
    report_path.write_text(report_md)
    log.info("Report written to %s", report_path)

    if not winner:
        log.info("No winner — skipping PR creation")
        return False

    # Write winning config
    winner_path = CANDIDATES_DIR / f"{today}-winner.yaml"
    winner_data = {
        "id": winner.candidate_id,
        "date": today,
        "score": compute_score(winner),
        "description": winner.description,
        "config": winner.config,
    }
    winner_path.write_text(yaml.dump(winner_data, default_flow_style=False))
    log.info("Winner config written to %s", winner_path)

    # Update champion
    champion_data = {
        "score": compute_score(winner),
        "date": today,
        "candidate_id": winner.candidate_id,
        "description": winner.description,
        "config": winner.config,
    }
    CHAMPION_PATH.write_text(yaml.dump(champion_data, default_flow_style=False))
    log.info("Champion updated: score=%.4f", compute_score(winner))

    # Git operations in opencastor-ops
    branch = f"harness-{today}"
    try:
        _run_git(["checkout", "-b", branch], cwd=OPS_REPO)
        _run_git(["add", "harness-research/"], cwd=OPS_REPO)
        _run_git(
            ["commit", "-m", f"feat(harness-research): results for {today}"],
            cwd=OPS_REPO,
        )
        _run_git(["push", "-u", "origin", branch], cwd=OPS_REPO)

        # Create PR
        pr_body = (
            f"## Harness Research Results — {today}\n\n"
            f"- **Winner:** {winner.candidate_id}\n"
            f"- **Score:** {compute_score(winner):.4f} (champion was {champion_score:.4f})\n"
            f"- **Description:** {winner.description}\n\n"
            f"See `harness-research/{today}.md` for full report.\n\n"
            f"Add label `approve-harness` to promote to OpenCastor."
        )
        subprocess.run(
            [
                "gh", "pr", "create",
                "--repo", "craigm26/opencastor-ops",
                "--head", branch,
                "--base", "main",
                "--title", f"harness-research: {today}",
                "--body", pr_body,
                "--label", "harness-candidate",
            ],
            cwd=OPS_REPO,
            check=True,
        )
        log.info("PR created on craigm26/opencastor-ops branch %s", branch)

        # Return to main
        _run_git(["checkout", "main"], cwd=OPS_REPO)
    except subprocess.CalledProcessError as e:
        log.error("Git/PR operation failed: %s\n%s", e, e.stderr)
        # Try to return to main
        try:
            _run_git(["checkout", "main"], cwd=OPS_REPO)
        except subprocess.CalledProcessError:
            pass
        raise

    return True
