"""Base protocol for autoresearch models."""
from typing import Protocol, Optional, runtime_checkable
import torch


@runtime_checkable
class TrainableModel(Protocol):
    def forward(self, idx: torch.Tensor, targets: Optional[torch.Tensor] = None, reduction: str = 'mean') -> torch.Tensor: ...
    def setup_optimizer(self, **kwargs) -> torch.optim.Optimizer: ...
    def init_weights(self) -> None: ...
    def estimate_flops(self) -> int: ...
    def num_scaling_params(self) -> dict: ...
